// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DBTx is an autogenerated mock type for the DBTx type
type DBTx struct {
	mock.Mock
}

type DBTx_Expecter struct {
	mock *mock.Mock
}

func (_m *DBTx) EXPECT() *DBTx_Expecter {
	return &DBTx_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with given fields:
func (_m *DBTx) Commit() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DBTx_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type DBTx_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *DBTx_Expecter) Commit() *DBTx_Commit_Call {
	return &DBTx_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *DBTx_Commit_Call) Run(run func()) *DBTx_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBTx_Commit_Call) Return(_a0 error) *DBTx_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBTx_Commit_Call) RunAndReturn(run func() error) *DBTx_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields:
func (_m *DBTx) Rollback() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DBTx_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type DBTx_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *DBTx_Expecter) Rollback() *DBTx_Rollback_Call {
	return &DBTx_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *DBTx_Rollback_Call) Run(run func()) *DBTx_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBTx_Rollback_Call) Return(_a0 error) *DBTx_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBTx_Rollback_Call) RunAndReturn(run func() error) *DBTx_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewDBTx creates a new instance of DBTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBTx {
	mock := &DBTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
