// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RegisterPort is an autogenerated mock type for the RegisterPort type
type RegisterPort struct {
	mock.Mock
}

type RegisterPort_Expecter struct {
	mock *mock.Mock
}

func (_m *RegisterPort) EXPECT() *RegisterPort_Expecter {
	return &RegisterPort_Expecter{mock: &_m.Mock}
}

// Ctx provides a mock function with given fields:
func (_m *RegisterPort) Ctx() (context.Context, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ctx")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func() (context.Context, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterPort_Ctx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ctx'
type RegisterPort_Ctx_Call struct {
	*mock.Call
}

// Ctx is a helper method to define mock.On call
func (_e *RegisterPort_Expecter) Ctx() *RegisterPort_Ctx_Call {
	return &RegisterPort_Ctx_Call{Call: _e.mock.On("Ctx")}
}

func (_c *RegisterPort_Ctx_Call) Run(run func()) *RegisterPort_Ctx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RegisterPort_Ctx_Call) Return(_a0 context.Context, _a1 error) *RegisterPort_Ctx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegisterPort_Ctx_Call) RunAndReturn(run func() (context.Context, error)) *RegisterPort_Ctx_Call {
	_c.Call.Return(run)
	return _c
}

// Email provides a mock function with given fields:
func (_m *RegisterPort) Email() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Email")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterPort_Email_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Email'
type RegisterPort_Email_Call struct {
	*mock.Call
}

// Email is a helper method to define mock.On call
func (_e *RegisterPort_Expecter) Email() *RegisterPort_Email_Call {
	return &RegisterPort_Email_Call{Call: _e.mock.On("Email")}
}

func (_c *RegisterPort_Email_Call) Run(run func()) *RegisterPort_Email_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RegisterPort_Email_Call) Return(_a0 string, _a1 error) *RegisterPort_Email_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegisterPort_Email_Call) RunAndReturn(run func() (string, error)) *RegisterPort_Email_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with given fields:
func (_m *RegisterPort) Name() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterPort_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type RegisterPort_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *RegisterPort_Expecter) Name() *RegisterPort_Name_Call {
	return &RegisterPort_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *RegisterPort_Name_Call) Run(run func()) *RegisterPort_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RegisterPort_Name_Call) Return(_a0 string, _a1 error) *RegisterPort_Name_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegisterPort_Name_Call) RunAndReturn(run func() (string, error)) *RegisterPort_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Password provides a mock function with given fields:
func (_m *RegisterPort) Password() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Password")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterPort_Password_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Password'
type RegisterPort_Password_Call struct {
	*mock.Call
}

// Password is a helper method to define mock.On call
func (_e *RegisterPort_Expecter) Password() *RegisterPort_Password_Call {
	return &RegisterPort_Password_Call{Call: _e.mock.On("Password")}
}

func (_c *RegisterPort_Password_Call) Run(run func()) *RegisterPort_Password_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RegisterPort_Password_Call) Return(_a0 string, _a1 error) *RegisterPort_Password_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegisterPort_Password_Call) RunAndReturn(run func() (string, error)) *RegisterPort_Password_Call {
	_c.Call.Return(run)
	return _c
}

// NewRegisterPort creates a new instance of RegisterPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegisterPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegisterPort {
	mock := &RegisterPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
