// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// nower is an autogenerated mock type for the nower type
type nower struct {
	mock.Mock
}

type nower_Expecter struct {
	mock *mock.Mock
}

func (_m *nower) EXPECT() *nower_Expecter {
	return &nower_Expecter{mock: &_m.Mock}
}

// Now provides a mock function with given fields:
func (_m *nower) Now() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// nower_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type nower_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *nower_Expecter) Now() *nower_Now_Call {
	return &nower_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *nower_Now_Call) Run(run func()) *nower_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *nower_Now_Call) Return(_a0 time.Time) *nower_Now_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *nower_Now_Call) RunAndReturn(run func() time.Time) *nower_Now_Call {
	_c.Call.Return(run)
	return _c
}

// newNower creates a new instance of nower. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newNower(t interface {
	mock.TestingT
	Cleanup(func())
}) *nower {
	mock := &nower{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
