// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcm

import (
	"database/sql"
)

type User struct {
	ID        int64
	Name      string
	Email     string
	Password  string
	CreatedAt sql.NullInt64
	UpdatedAt sql.NullInt64
}
